// In this file you can specify the trial data for your experiment

const practice_trials = {
  key_press_trials = [
    {
        question: "Are the objects the same?",
        picture: 'mental_rotation_images/3_50_different.jpg',
        number: 9,
        angle: 50,
        expected: 'different',
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
    },
    {
        question: "Are the objects the same?",
        picture: 'mental_rotation_images/3_50_same.jpg',
        number: 10,
        angle: 50,
        expected: 'same',
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
    },
    {
        question: "Are the objects the same?",
        picture: 'mental_rotation_images/3_150_different.jpg',
        number: 11,
        angle: 150,
        expected: 'different',
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
    },
    {
        question: "Are the objects the same?",
        picture: 'mental_rotation_images/3_150_same.jpg',
        number: 12,
        angle: 150,
        expected: 'same',
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
    },
    {
        question: "Are the objects the same?",
        picture: 'mental_rotation_images/4_50_different.jpg',
        number: 13,
        angle: 50,
        expected: 'different',
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
    },
    {
        question: "Are the objects the same?",
        picture: 'mental_rotation_images/4_50_same.jpg',
        number: 14,
        angle: 50,
        expected: 'same',
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
    },
    {
        question: "Are the objects the same?",
        picture: 'mental_rotation_images/4_150_different.jpg',
        number: 15,
        angle: 150,
        expected: 'different',
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
    },
    {
        question: "Are the objects the same?",
        picture: 'mental_rotation_images/4_150_same.jpg',
        number: 16,
        angle: 150,
        expected: 'same',
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
    },
    {
        question: "Are the objects the same?",
        picture: 'mental_rotation_images/5_50_different.jpg',
        number: 17,
        angle: 50,
        expected: 'different',
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
    },
    {
        question: "Are the objects the same?",
        picture: 'mental_rotation_images/5_50_same.jpg',
        number: 18,
        angle: 50,
        expected: 'same',
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
    },
    {
        question: "Are the objects the same?",
        picture: 'mental_rotation_images/5_150_different.jpg',
        number: 19,
        angle: 150,
        expected: 'different',
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
    },
    {
        question: "Are the objects the same?",
        picture: 'mental_rotation_images/5_150_same.jpg',
        number: 20,
        angle: 150,
        expected: 'same',
        key1: 'f',
        key2: 'j',
        f: 'same',
        j: 'different',
    },
  ],
};


const trial_info = {
  key_press_trials = [
      {
          question: "Are the objects the same?",
          picture: 'mental_rotation_images/1_50_different.jpg',
          number: 1,
          angle: 50,
          expected: 'different',
          key1: 'f',
          key2: 'j',
          f: 'same',
          j: 'different',
      },
      {
          question: "Are the objects the same?",
          picture: 'mental_rotation_images/1_50_same.jpg',
          number: 2,
          angle: 50,
          expected: 'same',
          key1: 'f',
          key2: 'j',
          f: 'same',
          j: 'different',
      },
      {
          question: "Are the objects the same?",
          picture: 'mental_rotation_images/1_150_different.jpg',
          number: 3,
          angle: 150,
          expected: 'different',
          key1: 'f',
          key2: 'j',
          f: 'same',
          j: 'different',
      },
      {
          question: "Are the objects the same?",
          picture: 'mental_rotation_images/1_150_same.jpg',
          number: 4,
          angle: 150,
          expected: 'same',
          key1: 'f',
          key2: 'j',
          f: 'same',
          j: 'different',
      },
      {
          question: "Are the objects the same?",
          picture: 'mental_rotation_images/2_50_different.jpg',
          number: 5,
          angle: 50,
          expected: 'different',
          key1: 'f',
          key2: 'j',
          f: 'same',
          j: 'different',
      },
      {
          question: "Are the objects the same?",
          picture: 'mental_rotation_images/2_50_same.jpg',
          number: 6,
          angle: 50,
          expected: 'same',
          key1: 'f',
          key2: 'j',
          f: 'same',
          j: 'different',
      },
      {
          question: "Are the objects the same?",
          picture: 'mental_rotation_images/2_150_different.jpg',
          number: 7,
          angle: 150,
          expected: 'different',
          key1: 'f',
          key2: 'j',
          f: 'same',
          j: 'different',
      },
      {
          question: "Are the objects the same?",
          picture: 'mental_rotation_images/2_150_same.jpg',
          number: 8,
          angle: 150,
          expected: 'same',
          key1: 'f',
          key2: 'j',
          f: 'same',
          j: 'different',
      },
      {
          question: "Are the objects the same?",
          picture: 'mental_rotation_images/6_50_different.jpg',
          number: 21,
          angle: 50,
          expected: 'different',
          key1: 'f',
          key2: 'j',
          f: 'same',
          j: 'different',
      },
      {
          question: "Are the objects the same?",
          picture: 'mental_rotation_images/6_50_same.jpg',
          number: 22,
          angle: 50,
          expected: 'same',
          key1: 'f',
          key2: 'j',
          f: 'same',
          j: 'different',
      },
      {
          question: "Are the objects the same?",
          picture: 'mental_rotation_images/6_150_different.jpg',
          number: 23,
          angle: 150,
          expected: 'different',
          key1: 'f',
          key2: 'j',
          f: 'same',
          j: 'different',
      },
      {
          question: "Are the objects the same?",
          picture: 'mental_rotation_images/6_150_same.jpg',
          number: 24,
          angle: 150,
          expected: 'same',
          key1: 'f',
          key2: 'j',
          f: 'same',
          j: 'different',
      },
      {
          question: "Are the objects the same?",
          picture: 'mental_rotation_images/7_50_different.jpg',
          number: 25,
          angle: 50,
          expected: 'different',
          key1: 'f',
          key2: 'j',
          f: 'same',
          j: 'different',
      },
      {
          question: "Are the objects the same?",
          picture: 'mental_rotation_images/7_50_same.jpg',
          number: 26,
          angle: 50,
          expected: 'same',
          key1: 'f',
          key2: 'j',
          f: 'same',
          j: 'different',
      },
      {
          question: "Are the objects the same?",
          picture: 'mental_rotation_images/7_150_different.jpg',
          number: 27,
          angle: 150,
          expected: 'different',
          key1: 'f',
          key2: 'j',
          f: 'same',
          j: 'different',
      },
      {
          question: "Are the objects the same?",
          picture: 'mental_rotation_images/7_150_same.jpg',
          number: 28,
          angle: 150,
          expected: 'same',
          key1: 'f',
          key2: 'j',
          f: 'same',
          j: 'different',
      },
      {
          question: "Are the objects the same?",
          picture: 'mental_rotation_images/8_50_different.jpg',
          number: 29,
          angle: 50,
          expected: 'different',
          key1: 'f',
          key2: 'j',
          f: 'same',
          j: 'different',
      },
      {
          question: "Are the objects the same?",
          picture: 'mental_rotation_images/8_50_same.jpg',
          number: 30,
          angle: 50,
          expected: 'same',
          key1: 'f',
          key2: 'j',
          f: 'same',
          j: 'different',
      },
      {
          question: "Are the objects the same?",
          picture: 'mental_rotation_images/8_150_different.jpg',
          number: 31,
          angle: 150,
          expected: 'different',
          key1: 'f',
          key2: 'j',
          f: 'same',
          j: 'different',
      },
      {
          question: "Are the objects the same?",
          picture: 'mental_rotation_images/8_150_same.jpg',
          number: 32,
          angle: 150,
          expected: 'same',
          key1: 'f',
          key2: 'j',
          f: 'same',
          j: 'different',
      },
      {
          question: "Are the objects the same?",
          picture: 'mental_rotation_images/9_50_different.jpg',
          number: 33,
          angle: 50,
          expected: 'different',
          key1: 'f',
          key2: 'j',
          f: 'same',
          j: 'different',
      },
      {
          question: "Are the objects the same?",
          picture: 'mental_rotation_images/9_50_same.jpg',
          number: 34,
          angle: 50,
          expected: 'same',
          key1: 'f',
          key2: 'j',
          f: 'same',
          j: 'different',
      },
      {
          question: "Are the objects the same?",
          picture: 'mental_rotation_images/9_150_different.jpg',
          number: 35,
          angle: 150,
          expected: 'different',
          key1: 'f',
          key2: 'j',
          f: 'same',
          j: 'different',
      },
      {
          question: "Are the objects the same?",
          picture: 'mental_rotation_images/9_150_same.jpg',
          number: 36,
          angle: 150,
          expected: 'same',
          key1: 'f',
          key2: 'j',
          f: 'same',
          j: 'different',
      },
      {
          question: "Are the objects the same?",
          picture: 'mental_rotation_images/10_50_different.jpg',
          number: 37,
          angle: 50,
          expected: 'different',
          key1: 'f',
          key2: 'j',
          f: 'same',
          j: 'different',
      },
      {
          question: "Are the objects the same?",
          picture: 'mental_rotation_images/10_50_same.jpg',
          number: 38,
          angle: 50,
          expected: 'same',
          key1: 'f',
          key2: 'j',
          f: 'same',
          j: 'different',
      },
      {
          question: "Are the objects the same?",
          picture: 'mental_rotation_images/10_150_different.jpg',
          number: 39,
          angle: 150,
          expected: 'different',
          key1: 'f',
          key2: 'j',
          f: 'same',
          j: 'different',
      },
      {
          question: "Are the objects the same?",
          picture: 'mental_rotation_images/10_150_same.jpg',
          number: 40,
          angle: 150,
          expected: 'same',
          key1: 'f',
          key2: 'j',
          f: 'same',
          j: 'different',
      },
      {
          question: "Are the objects the same?",
          picture: 'mental_rotation_images/11_50_different.jpg',
          number: 41,
          angle: 50,
          expected: 'different',
          key1: 'f',
          key2: 'j',
          f: 'same',
          j: 'different',
      },
      {
          question: "Are the objects the same?",
          picture: 'mental_rotation_images/11_50_same.jpg',
          number: 42,
          angle: 50,
          expected: 'same',
          key1: 'f',
          key2: 'j',
          f: 'same',
          j: 'different',
      },
      {
          question: "Are the objects the same?",
          picture: 'mental_rotation_images/11_150_different.jpg',
          number: 43,
          angle: 150,
          expected: 'different',
          key1: 'f',
          key2: 'j',
          f: 'same',
          j: 'different',
      },
      {
          question: "Are the objects the same?",
          picture: 'mental_rotation_images/11_150_same.jpg',
          number: 44,
          angle: 150,
          expected: 'same',
          key1: 'f',
          key2: 'j',
          f: 'same',
          j: 'different',
      },
      {
          question: "Are the objects the same?",
          picture: 'mental_rotation_images/12_50_different.jpg',
          number: 45,
          angle: 50,
          expected: 'different',
          key1: 'f',
          key2: 'j',
          f: 'same',
          j: 'different',
      },
      {
          question: "Are the objects the same?",
          picture: 'mental_rotation_images/12_50_same.jpg',
          number: 46,
          angle: 50,
          expected: 'same',
          key1: 'f',
          key2: 'j',
          f: 'same',
          j: 'different',
      },
      {
          question: "Are the objects the same?",
          picture: 'mental_rotation_images/12_150_different.jpg',
          number: 47,
          angle: 150,
          expected: 'different',
          key1: 'f',
          key2: 'j',
          f: 'same',
          j: 'different',
      },
      {
          question: "Are the objects the same?",
          picture: 'mental_rotation_images/12_150_same.jpg',
          number: 48,
          angle: 150,
          expected: 'same',
          key1: 'f',
          key2: 'j',
          f: 'same',
          j: 'different',
      },
      {
          question: "Are the objects the same?",
          picture: 'mental_rotation_images/13_50_different.jpg',
          number: 49,
          angle: 50,
          expected: 'different',
          key1: 'f',
          key2: 'j',
          f: 'same',
          j: 'different',
      },
      {
          question: "Are the objects the same?",
          picture: 'mental_rotation_images/13_50_same.jpg',
          number: 50,
          angle: 50,
          expected: 'same',
          key1: 'f',
          key2: 'j',
          f: 'same',
          j: 'different',
      },
      {
          question: "Are the objects the same?",
          picture: 'mental_rotation_images/13_150_different.jpg',
          number: 51,
          angle: 150,
          expected: 'different',
          key1: 'f',
          key2: 'j',
          f: 'same',
          j: 'different',
      },
      {
          question: "Are the objects the same?",
          picture: 'mental_rotation_images/13_150_same.jpg',
          number: 52,
          angle: 150,
          expected: 'same',
          key1: 'f',
          key2: 'j',
          f: 'same',
          j: 'different',
      },
      {
          question: "Are the objects the same?",
          picture: 'mental_rotation_images/14_50_different.jpg',
          number: 53,
          angle: 50,
          expected: 'different',
          key1: 'f',
          key2: 'j',
          f: 'same',
          j: 'different',
      },
      {
          question: "Are the objects the same?",
          picture: 'mental_rotation_images/14_50_same.jpg',
          number: 54,
          angle: 50,
          expected: 'same',
          key1: 'f',
          key2: 'j',
          f: 'same',
          j: 'different',
      },
      {
          question: "Are the objects the same?",
          picture: 'mental_rotation_images/14_150_different.jpg',
          number: 55,
          angle: 150,
          expected: 'different',
          key1: 'f',
          key2: 'j',
          f: 'same',
          j: 'different',
      },
      {
          question: "Are the objects the same?",
          picture: 'mental_rotation_images/14_150_same.jpg',
          number: 56,
          angle: 150,
          expected: 'same',
          key1: 'f',
          key2: 'j',
          f: 'same',
          j: 'different',
      },
      {
          question: "Are the objects the same?",
          picture: 'mental_rotation_images/15_50_different.jpg',
          number: 57,
          angle: 50,
          expected: 'different',
          key1: 'f',
          key2: 'j',
          f: 'same',
          j: 'different',
      },
      {
          question: "Are the objects the same?",
          picture: 'mental_rotation_images/15_50_same.jpg',
          number: 58,
          angle: 50,
          expected: 'same',
          key1: 'f',
          key2: 'j',
          f: 'same',
          j: 'different',
      },
      {
          question: "Are the objects the same?",
          picture: 'mental_rotation_images/15_150_different.jpg',
          number: 59,
          angle: 150,
          expected: 'different',
          key1: 'f',
          key2: 'j',
          f: 'same',
          j: 'different',
      },
      {
          question: "Are the objects the same?",
          picture: 'mental_rotation_images/15_150_same.jpg',
          number: 60,
          angle: 150,
          expected: 'same',
          key1: 'f',
          key2: 'j',
          f: 'same',
          j: 'different',
      },
    ],
  };
